[project]
name = "ppgeec2316"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Raphael Ramos", email = "raphael.opensource@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=7.3.0",
    "matplotlib>=3.11.1",
    "pytest>=9.1.1",
]

[project.scripts]
ppgeec2316 = "ppgeec2316:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"

[tool.uv]
package = false

[dependency-groups]
dev = [
    "nbconvert>=7.17.1",
]
